---

# Use Ansible to configure your 'primary Ethernet interface' as follows:
# interface description:    *** IN USE ***
# switchport mode:          access
# VLAN:                     <one of the VLANs created in exercise1>
# Your 'primary Ethernet interface' is specified in your ~/ansible-hosts file.
# If your primary interface is already 'IN USE' (by someone else), then use your secondary interface (once again specified in ~/ansible-hosts).
# You can determine if an interface is already in use by SSH'ing into the switch. Reminder, do NOT use Ethernet1.

# This Ansible play-book use module: eos_interface.py
# /home/pmontero/ANSIBLE/library/eos_interface.py

# pynet-sw3#show int description | include Et5|Et6
# Interface                      Status         Protocol Description
# Et5                            up             up
# Et6                            up             up


- name: EX2 Using Ansible to configure Arista vEOS.
  hosts: arista

  tasks:
    - name: Configure primary interface description (Et5)
      eos_interface: name=Ethernet5 description="*** IN USE ***"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Configure primary interface (Et5) switchport mode to access with vlan-id 900
      eos_switchport: name=Ethernet5 mode=access access_vlan=900
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
